name: Generate trophy card

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy.svg
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ${{ github.repository_owner }}
          output_path: trophy.svg
          token: ${{ secrets.TROPHY_TOKEN }}
          theme: tokyonight
          max-rows: 1
          margin-width: 8
          margin-height: 8
          no-background: true
          no-frame: false

      - name: Commit trophy.svg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add trophy.svg

          git commit -m "chore: update GitHub trophy card" || exit 0

          git push
